In [1]:
import numpy as np

In [2]:
python_list = [1,2,3]

# chuyen doi danh sach python sang numpy list
numpy_list = np.array(python_list)
type(numpy_list)

numpy.ndarray

In [3]:
my_list = [1, 'chap', True, 2.0]

In [4]:
my_list = [1, 2, 3, 4.5]
np_list = np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [5]:
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [6]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8]) # x = np.arange(1, 9)

In [7]:
print(x[3])

4


In [8]:
# lay nhieu hon 1 phan tu
# cong thuc: array[start:end:step]
# lay 1 2 3

x[0:3]

array([1, 2, 3])

In [9]:
# lay tu 3 - 8 theo 2 cach

# c1
x[2:8]

array([3, 4, 5, 6, 7, 8])

In [10]:
# c2
x[2:]

array([3, 4, 5, 6, 7, 8])

In [11]:
# lay 3 va 5
x[2], x[4]

(np.int64(3), np.int64(5))

In [12]:
np_list = np.array([[1,2], [3,4], [5,6]])

In [13]:
# lay 6
np_list[2][1]

np.int64(6)

In [14]:
# lay [3,4],[5,6]

# c1
np_list[1:3]

array([[3, 4],
       [5, 6]])

In [15]:
# c2
np_list[1:] 

array([[3, 4],
       [5, 6]])

In [16]:
# c3
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [17]:
# lay 1,5

# c1
np_list[0::2,0]

array([1, 5])

In [18]:
# c2
np_list[[0,2],0]

array([1, 5])

In [19]:
x = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
np_list[0:,1]  # lay 2,8

array([ 2,  6, 10, 14])

In [21]:
# lay 7, 11
np_list[[1,2],2]

array([ 7, 11])

In [22]:
# lay 3 7 10
# c1
np_list[[0,1,2],[3,2,1]]


array([ 4,  7, 10])

In [23]:
# lay 16 15 14 13
# c1
np_list[3,::-1]

array([16, 15, 14, 13])

In [24]:
# c2
np_list[[3],[3,2,1,0]]

array([16, 15, 14, 13])

In [25]:
# c3
np_list[[3,3,3,3],[3,2,1,0]]

array([16, 15, 14, 13])

In [26]:
# c4
np_list[[-1],[3,2,1,0]]

array([16, 15, 14, 13])

In [ ]:
# btvn 1
# cho ma tran [[99, 99, 99],
#              [99, 99, 99]
#              [99, 99, 99]]

# hay tuong tuong o 99 trong
# gia su 1 la x
# gia su 0 la 0

# lay dau vao tu phia x va phia o luan phien
# neu dau vao ti phia x la (0,0)

# thi ma tra se la
# [[x, 99, 99],
#  [99, 99, 99],
#  [99, 99, 99]]

# neu dau vao tu phi 0 cung la (0,0) thi thong bao ho nhap lai
# neu khong thi dien vao ma tran

# thu thach: neu nguoi dau tien co 3 phan tu lien tiep thi dung tro choi

In [ ]:
import numpy as np

# hàm nhập vị trí người chơi A
def a_input():
    xa,ya=list(input("\nNhap vi tri nguoi choi A: ").split(','))
    return xa,ya

# hàm nhập vị trí người chơi B
def b_input():
    xb,yb=list(input("\nNhap vi tri nguoi choi B: ").split(','))
    return xb,yb

# hàm kiểm tra vị trí người chơi A có hợp lệ hay không, nếu không hợp lệ thì yêu cầu nhập lại
def a_validate(matrix, xa, ya):
    
    while matrix[int(xa)][int(ya)] != 99:
        
        xa, ya = a_input()
        
        if matrix[int(xa)][int(ya)] == 99:
            break
        
        elif matrix[int(xa)][int(ya)] ==1:
            print("\nVi tri da duoc ban chon, vui long chon vi tri khac")
            continue
        
        else:
            print("\nVi tri da duoc nguoi choi B, vui long chon vi tri khac")
            continue
    
    matrix[int(xa)][int(ya)] = '1'
    print("\n",matrix)
    return matrix, xa, ya

# hàm kiểm tra vị trí người chơi B có hợp lệ hay không, nếu không hợp lệ thì yêu cầu nhập lại
def b_validate(matrix, xb, yb):
    
    while matrix[int(xb)][int(yb)] != 99:
        
        xb, yb = b_input()
        
        if matrix[int(xb)][int(yb)] == 99:
            break
        
        elif matrix[int(xb)][int(yb)] ==0:
            print("\nVi tri da duoc ban chon, vui long chon vi tri khac")
            continue
        
        elif matrix[int(xb)][int(yb)] ==1:
            print("\nVi tri da duoc nguoi choi A, vui long chon vi tri khac")
            continue
        
        else:
            print("\nVi tri khong hop le, vui long chon vi tri khac")
            continue
    
    matrix[int(xb)][int(yb)] = '0'
    print("\n",matrix)
    return matrix, xb, yb

# hàm boolean kiểm tra điều kiện chiến thắng tick tack toe 
def win(matrix):
    
    # kiểm tra các hàng, cột và đường chéo để xác định người chiến thắng
    # nếu tìm ra người chiến thắng thì trả về True, ngược lại trả về False
    
    if (matrix[0, 0:3] == 1).all() or (matrix[1, 0:3] == 1).all() or (matrix[2, 0:3] == 1).all() or (matrix[0:3, 0] == 1).all() or (matrix[0:3, 1] == 1).all() or (matrix[0:3, 2] == 1).all() or (matrix.diagonal() == 1).all() or (np.fliplr(matrix).diagonal() == 1).all():
        print("=== Nguoi choi A da chien thang! ===")
        return True
    
    elif (matrix[0, 0:3] == 0).all() or (matrix[1, 0:3] == 0).all() or (matrix[2, 0:3] == 0).all() or (matrix[0:3, 0] == 0).all() or (matrix[0:3, 1] == 0).all() or (matrix[0:3, 2] == 0).all() or (matrix.diagonal() == 0).all() or (np.fliplr(matrix).diagonal() == 0).all():
        print("=== Nguoi choi B da chien thang! ===")
        return True
    
    else: 
        return False

matrix = np.array([[99,99,99],
                   [99,99,99],
                   [99,99,99]]) 

# vòng lặp chính của trò chơi, nếu chưa tìm ra được người chiến thắng thì trò chơi sẽ tiếp tục
while win(matrix) == False:
        
    xa,ya = a_input()
    a_validate(matrix, xa, ya)

    xb,yb = b_input()
    b_validate(matrix, xb, yb)


        
        

In [ ]:
# btvn 2
y = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [51]:
# lay 4,5,6
y[1:2]

array([[4, 5, 6]])

In [52]:
# lay 2,5
y[[0,1],[1]]

array([2, 5])

In [54]:
# lay 3,4
y[[0,1],[2,0]]

array([3, 4])

In [55]:
# lay 9,6,3
y[[2,1,0],[2]]

array([9, 6, 3])

In [29]:
# btvn 3

# cho x = [1,2,3,4,5,6,7,8,9,10]

# 1. xuat ra tat ca cac so chan trong x su dung if
# 2. xuat ra tat ca cac so chan trong x su dung list comprehension


In [59]:
x = [1,2,3,4,5,6,7,8,9,10]
z = []
x

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [62]:
# 1
for i in x:
    if i%2==0:
        z.append(i)
        
z

[2, 4, 6, 8, 10]

In [63]:
# 2
z = [i for i in x if i%2==0]
z

[2, 4, 6, 8, 10]

In [30]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [32]:
np_x%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [33]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
idx = [ True, False, True, False, True, False, True, False, True, False]
np_x[idx]

array([0, 2, 4, 6, 8])

In [35]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x >0

np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# btvn 
# tao mot mang numpy co kich thuoc 150x5, gia su mang nay chua 150 mau du lieu cua sv bao gom chieu cao, can nang, tuoi, luong va diem trung binh
# tach mang dua tren 4 cot dau tien thanh mot bien co ten la X va cot cuoi cung thanh bien co ten la y
# tach X thanh 2 bien X_train va X_test, trong do X_test chua 30% du lieu ban dau va 
# tach y thanh 2 bien Y_train va y_test, trong do Y_test chua 30% du lieu ban dau

# tao 10 tap du lieu X_train khong chong cheo len nhau

In [121]:
from sklearn.model_selection import train_test_split

In [118]:
# tao mot mang numpy co kich thuoc 150x5, gia su mang nay chua 150 mau du lieu cua sv bao gom chieu cao, can nang, tuoi, luong va diem trung binh
np.random.seed(42)
data = np.random.rand(150, 5)

In [119]:
# tach mang dua tren 4 cot dau tien thanh mot bien co ten la X va cot cuoi cung thanh bien co ten la y
X = data[:, :4]   
y = data[:, 4]  
print(X.shape)  
print(y.shape) 

(150, 4)
(150,)


In [122]:
# tach X thanh 2 bien X_train va X_test, trong do X_test chua 30% du lieu ban dau va 
# tach y thanh 2 bien Y_train va y_test, trong do Y_test chua 30% du lieu ban dau
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

X_train: (105, 4)
X_test : (45, 4)


In [ ]:
# tao 10 tap du lieu X_train khong chong cheo len nhau
X_train_splits = np.array_split(X_train, 10)

# kiểm tra kích thước từng tập
for i, split in enumerate(X_train_splits):
    print(f"Tap {i+1}: {split.shape}")

Tap 1: (11, 4)
Tap 2: (11, 4)
Tap 3: (11, 4)
Tap 4: (11, 4)
Tap 5: (11, 4)
Tap 6: (10, 4)
Tap 7: (10, 4)
Tap 8: (10, 4)
Tap 9: (10, 4)
Tap 10: (10, 4)
